# Generated by Django 3.1.4 on 2020-12-07 18:05

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201207_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/default.jpg', upload_to=courses.models.upload_to, verbose_name='Image'),
        ),
    ]
